{
 "title": "Canopy dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(canopy_bft_height,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node status ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stake amount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CNPY" } },
   "targets": [
    {
     "expr": "canopy_validator_stake_amount{job=\"canopy\"}",
     "legendFormat": "{{instance}}:{{address}}"
    }
   ]
  },
  {
   "title": "Account Balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CNPY" } },
   "targets": [
    {
     "expr": "canopy_account_balance{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{address}}"
    }
   ]
  },
  {
   "title": "Node sync",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "canopy_syncing_status{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validator status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "canopy_node_status{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validator status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_status{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validator type",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_compounding{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compounding status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_validator_compounding{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "canopy_peer_total{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers Outbound",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_peer_outbound{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers inbound",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_peer_inbound{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers Inbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "canopy_peer_inbound{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers outbound",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Peers" } },
   "targets": [
    {
     "expr": "canopy_peer_outbound{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Block height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "canopy_bft_height{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Processing  time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_block_processing_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Processing time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(canopy_block_processing_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "canopy_block_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Largest TX Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_largest_txn{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total transactions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_transaction_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block height",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_height{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root height",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_root_height{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Largest TX Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "canopy_block_largest_txn{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root chain info time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_root_chain_info_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Root chain info time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(canopy_root_chain_info_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT propose vote time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_propose_vote_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT propose vote time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_election_vote_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block VDFI iterations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "canopy_block_vdf_iterations{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block VDFI Interations",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_vdf_iterations{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "BFT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "BFT Rounds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Rounds" } },
   "targets": [
    {
     "expr": "canopy_bft_round{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT Rounds",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Rounds" } },
   "targets": [
    {
     "expr": "canopy_bft_round{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT election vote time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_election_vote_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT election vote time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_election_vote_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT propose time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_propose_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT propose time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_propose_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT precommit vote time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_precommit_vote_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT precommit vote time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_precommit_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT election time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_election_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BFT election time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_election_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non signer percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "canopy_block_non_signer_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non signer percentage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_block_non_signer_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT commit time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(canopy_bft_commit_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BFT commit time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_bft_commit_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "MempoolSize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "canopy_mempool_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MempoolSize",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_mempool_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MempoolCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "Txs" } },
   "targets": [
    {
     "expr": "canopy_mempool_tx_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Tx count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_mempool_tx_count{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(canopy_store_commit_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(canopy_store_commit_time_sum{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "canopy_store_partition_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_store_partition_time_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "canopy_store_commit_entries{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Entries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_store_commit_entries{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition Entries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "canopy_store_partition_entries{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition Entries",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_store_partition_entries{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "canopy_store_commit_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Commit  Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_store_commit_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "canopy_store_partition_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Partition  Size",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "canopy_store_partition_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}